# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ray < Formula
  desc "A high-performance systems engineering CLI."
  homepage "https://github.com/V3DxNT/Ray"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/V3DxNT/Ray/releases/download/v1.0.2/ray_1.0.2_darwin_amd64.tar.gz"
      sha256 "d6b43da4d6fcf1bb0aa49ee07ff5b5b777ee6a08b7da2b15283570be26df8fe7"

      define_method(:install) do
        bin.install "ray"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/V3DxNT/Ray/releases/download/v1.0.2/ray_1.0.2_darwin_arm64.tar.gz"
      sha256 "a50ecf41e2da2bd35151b6cc6cb96d144387a07a0a92bc45cbfba6e3083983d9"

      define_method(:install) do
        bin.install "ray"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/V3DxNT/Ray/releases/download/v1.0.2/ray_1.0.2_linux_amd64.tar.gz"
      sha256 "9171fa335853e27fb3ec5caf71b6f62d14a58530d6b4f29a9dbe4349f2b8f8dd"
      define_method(:install) do
        bin.install "ray"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/V3DxNT/Ray/releases/download/v1.0.2/ray_1.0.2_linux_arm64.tar.gz"
      sha256 "671a5d655e3865c9447cd6bd4af76bdcbf5c5e1fbe18be38fdac606606b58f00"
      define_method(:install) do
        bin.install "ray"
      end
    end
  end
end
